spring:
  profiles:
    active: dev


---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:1234/tingting?serverTimezone=Asia/Shanghai
    username: user
    password: pwd

# enable swagger3
springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: info
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%thread] [%logger{15}] %msg%n'
  file:
    name: ./log/app.log
    max-size: 50MB
    total-size-cap: 1GB
